# a docker-compose file with a postgres 14 service

version: '3.8'
services:
  corpusx:
    build:
        context: .
        dockerfile: ./dockerfiles/Dockerfile
    container_name: corpusx
    ports:
      - "8000:8000"
    environment:
        - POSTGRES_NAME=postgres
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_HOST=dbcorpus
        - REDIS_HOST=rediscorpus
        - CORS_ORIGIN_WHITELIST=http://localhost,http://localhost:4200,http://172.31.0.5
        - ALLOWED_HOSTS=localhost,172.31.0.5
    networks:
      - corpusx-net
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
  corpusx-worker:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    container_name: corpusx-worker
    command: python manage.py rqworker default
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=dbcorpus
      - REDIS_HOST=rediscorpus
    networks:
      - corpusx-net
    volumes:
      - ./media:/app/media
  nginx:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./media:/media/
      - ./staticfiles:/static/
    depends_on:
      - corpusx
    networks:
      - corpusx-net
  dbcorpus:
    container_name: dbcorpus
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
    - "5432:5432"
    volumes:
    - ./data:/var/lib/postgresql/data
    networks:
      - corpusx-net
  rediscorpus:
    container_name: rediscorpus
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-redis
    restart: always
    environment:
      - REDIS_PASSWORD=redis
    ports:
      - "6379:6379"
    networks:
      - corpusx-net

networks:
    corpusx-net:
