# Generated by Django 5.0 on 2023-12-09 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cephalon', '0002_file_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='ProjectFile',
        ),
    ]
