# Generated by Django 5.0 on 2023-12-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephalon', '0003_rename_file_projectfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='temporary',
            field=models.BooleanField(default=False),
        ),
    ]
