# Generated by Django 5.0 on 2023-12-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephalon', '0004_project_temporary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkedUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.UUIDField(db_index=True, unique=True)),
                ('filename', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='cephalon/files/chunks/')),
                ('offset', models.BigIntegerField(blank=True, null=True)),
                ('hash', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_size', models.BigIntegerField(default=4096)),
                ('total_size', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('complete', 'complete')], default='pending', max_length=11)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
