# Generated by Django 5.0 on 2023-12-10 16:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephalon', '0005_chunkedupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkedupload',
            name='upload_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
