# Generated by Django 5.0 on 2023-12-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephalon', '0006_alter_chunkedupload_upload_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkedupload',
            name='offset',
            field=models.BigIntegerField(default=0),
        ),
    ]
