# Generated by Django 5.0 on 2023-12-10 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephalon', '0007_alter_chunkedupload_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkedupload',
            name='chunk_size',
            field=models.BigIntegerField(default=1048576),
        ),
        migrations.CreateModel(
            name='ProjectFileContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='cephalon.projectfile')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
