# Generated by Django 5.0 on 2023-12-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephalon', '0009_apikeyremote_topic_apikey_access_all_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='load_file_content',
            field=models.BooleanField(default=False),
        ),
    ]
