# Generated by Django 5.0 on 2023-12-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephalon', '0010_projectfile_load_file_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='path',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
