# Generated by Django 5.0 on 2023-12-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephalon', '0011_projectfile_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkedupload',
            name='file_category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='file_category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
