# Generated by Django 5.0 on 2023-12-15 12:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephalon', '0013_apikey_user_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='access_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='project',
            field=models.ManyToManyField(blank=True, to='cephalon.project'),
        ),
        migrations.AddField(
            model_name='topic',
            name='projects',
            field=models.ManyToManyField(blank=True, to='cephalon.project'),
        ),
    ]
