# Generated by Django 5.0 on 2023-12-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephalon', '0014_apikey_access_id_apikey_project_topic_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='access_id',
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.TextField(db_index=True, unique=True),
        ),
    ]
