# Generated by Django 5.0 on 2023-12-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephalon', '0015_remove_apikey_access_id_alter_apikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='hash',
            field=models.TextField(blank=True, null=True),
        ),
    ]
