# Generated by Django 5.0 on 2023-12-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephalon', '0016_alter_project_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='hash',
            field=models.TextField(blank=True, null=True),
        ),
    ]
