# Generated by Django 5.0 on 2023-12-15 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephalon', '0017_alter_projectfile_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfilecontent',
            name='project_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='cephalon.projectfile'),
        ),
    ]
