# Generated by Django 5.0 on 2023-12-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephalon', '0018_alter_projectfilecontent_project_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
