# Generated by Django 5.0 on 2023-12-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephalon', '0019_project_encrypted'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsocketInterchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='apikey',
            name='interchanges',
            field=models.ManyToManyField(blank=True, to='cephalon.websocketinterchange'),
        ),
    ]
