# Generated by Django 5.0 on 2023-12-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cephalon', '0020_websocketinterchange_apikey_interchanges'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebsocketInterchange',
            new_name='Pyre',
        ),
        migrations.RenameField(
            model_name='apikey',
            old_name='interchanges',
            new_name='pyres',
        ),
    ]
