# Generated by Django 5.0 on 2023-12-18 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephalon', '0023_websocketsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='remote_pair',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_pair', to='cephalon.apikeyremote'),
        ),
    ]
