# Generated by Django 5.0 on 2023-12-21 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephalon', '0024_apikey_remote_pair'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsocketNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='websocket_nodes', to='cephalon.apikey')),
            ],
        ),
        migrations.AddField(
            model_name='pyre',
            name='file_request_channel_connected_nodes',
            field=models.ManyToManyField(blank=True, related_name='file_request_channel', to='cephalon.websocketnode'),
        ),
        migrations.AddField(
            model_name='pyre',
            name='interserver_channel_connected_nodes',
            field=models.ManyToManyField(blank=True, related_name='interserver_channel', to='cephalon.websocketnode'),
        ),
        migrations.AddField(
            model_name='pyre',
            name='result_request_channel_connected_nodes',
            field=models.ManyToManyField(blank=True, related_name='result_request_channel', to='cephalon.websocketnode'),
        ),
        migrations.AddField(
            model_name='pyre',
            name='search_data_channel_connected_nodes',
            field=models.ManyToManyField(blank=True, related_name='search_data_channel', to='cephalon.websocketnode'),
        ),
    ]
