# Generated by Django 5.0 on 2023-12-21 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cephalon', '0025_websocketnode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pyre',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='websocketnode',
            options={'ordering': ['id']},
        ),
    ]
