# Generated by Django 5.0 on 2023-12-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephalon', '0026_alter_pyre_options_alter_websocketnode_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyre',
            name='topics',
            field=models.ManyToManyField(blank=True, to='cephalon.topic'),
        ),
    ]
