# Generated by Django 5.0 on 2023-12-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephalon', '0027_pyre_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file_type',
            field=models.CharField(choices=[('csv', 'csv'), ('tsv', 'tsv'), ('txt', 'tabulated text'), ('json', 'json'), ('other', 'other')], default='tsv', max_length=5),
        ),
    ]
