# Generated by Django 5.0 on 2023-12-24 13:54

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephalon', '0028_alter_projectfile_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_query', models.TextField(blank=True, null=True)),
                ('search_type', models.TextField(blank=True, null=True)),
                ('search_id', models.TextField(blank=True, null=True)),
                ('search_status', models.CharField(choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('complete', 'complete'), ('failed', 'failed')], default='pending', max_length=11)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='projectfilecontent',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='file_category',
            field=models.CharField(choices=[('unprocessed', 'unprocessed'), ('searched', 'searched'), ('differential_analysis', 'differential_analysis'), ('sample_annotation', 'sample_annotation'), ('comparison_matrix', 'comparison_matrix'), ('other', 'other')], default='other', max_length=30),
        ),
        migrations.AddIndex(
            model_name='projectfilecontent',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='cephalon_pr_search__0ed348_gin'),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='cephalon.projectfile'),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='cephalon.websocketsession'),
        ),
    ]
