# Generated by Django 5.0 on 2023-12-24 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephalon', '0029_searchresult_projectfilecontent_search_vector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchresult',
            name='data',
        ),
        migrations.AddField(
            model_name='searchresult',
            name='client_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='file_hash',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='cephalon.websocketnode'),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='pyre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='cephalon.pyre'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='cephalon/files/search_results/'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='search_query',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
