# Generated by Django 5.0 on 2023-12-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephalon', '0030_remove_searchresult_data_searchresult_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='allow_download',
            field=models.BooleanField(default=False),
        ),
    ]
