# Generated by Django 5.0 on 2023-12-29 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephalon', '0031_apikey_allow_download'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comparison_matrix_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparison_matrix_related_files', to='cephalon.projectfile')),
                ('differential_analysis_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='differential_analysis_related_files', to='cephalon.projectfile')),
                ('other_files', models.ManyToManyField(blank=True, related_name='other_related_files', to='cephalon.projectfile')),
                ('sample_annotation_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_annotation_related_files', to='cephalon.projectfile')),
                ('searched_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searched_related_files', to='cephalon.projectfile')),
                ('unprocessed_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unprocessed_related_files', to='cephalon.projectfile')),
            ],
        ),
    ]
