# Generated by Django 5.0.1 on 2024-01-07 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cephalon', '0032_analysisgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisgroup',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_groups', to='cephalon.project'),
        ),
    ]
